from matplotlib import pyplot as plt
import cv2

img = cv2.imread("4.jpg")
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.figure(figsize=(10, 10))
plt.imshow(img)
plt.axis("off")
plt.title("Original")
plt.show()

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
gray = cv2.medianBlur(gray, 5)
plt.figure(figsize=(10, 10))
plt.imshow(gray, cmap="gray")
plt.axis("off")
plt.title("Gray")
plt.show()

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
edge = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 9, 9)
invert = cv2.bitwise_not(gray)
blur = cv2.GaussianBlur(invert, (21, 21), 0)
invertedblur = cv2.bitwise_not(blur)
sketch_filter = cv2.divide(gray, invertedblur, scale=256.0)
plt.figure(figsize=(10, 10))
plt.imshow(sketch_filter, cmap="gray")
plt.axis("off")
plt.title("Sketch")
plt.show()

edges = cv2.Canny(gray, 100, 200)
color = cv2.bilateralFilter(img, 9, 250, 250)
cartoon = cv2.bitwise_and(color, color, mask=edge)
plt.figure(figsize=(10, 10))
plt.imshow(cartoon, cmap="gray")
plt.axis("off")
plt.title("Cartoon")
plt.show()
